title: Tyson's Blog
description: Notes on tech and life
author: Tyson

theme: minima

markdown: kramdown

timezone: America/New_York

permalink: /:year/:month/:day/:title/

minima:
  skin: dark    # 可选：dark / classic / solarized
