title: 安徽通程智能无人机基地
description: 关于无人机、关于政策、关于技术、关于市场、关于应用
author: 叶老师

theme: jekyll-theme-slate

markdown: kramdown

timezone: America/New_York

permalink: /:year/:month/:day/:title/

github:
  is_project_page: false

  show_downloads: false
