title: 安徽通程智能无人机基地
description: 专注无人机应用、培训与行业服务
lang: zh-CN
author: 叶老师

theme: cjekyll-theme-cayman

markdown: kramdown

timezone: America/New_York

permalink: /:year/:month/:day/:title/

github:
  is_project_page: false


  lang: zh-CN

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: default


